import { type Module, inject } from 'langium';
import {
    createDefaultModule,
    createDefaultSharedModule,
    type DefaultSharedModuleContext,
    type LangiumServices,
    type LangiumSharedServices,
    type PartialLangiumServices,
} from 'langium/lsp';
import {
    SdvmlGeneratedModule,
    SdvmlGeneratedSharedModule,
} from './generated/module.js';
import {
    SdvmlValidator,
    registerValidationChecks,
} from './sdvml-validator.js';

// NEW IMPORTS FOR SPROTTY
import { LangiumSprottyServices, SprottyDefaultModule, SprottyDiagramServices, SprottySharedServices, SprottySharedModule, LangiumSprottySharedServices} from 'langium-sprotty';
import { SdvmlDiagramGenerator } from '../diagram/sdvml-diagram-generator.js'; // Adjust path if you put it in a 'diagram' folder


/**
 * The module that adds Sprotty services to the SDVML language.
 */


export const SdvmlSprottyModule: Module<PartialLangiumServices& LangiumSprottyServices & SdvmlAddedServices & SprottySharedServices, SprottyDiagramServices > = { // Use PartialLangiumServices here
    diagram: {
        DiagramGenerator: (services) => new SdvmlDiagramGenerator(services)
    }
};

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SdvmlAddedServices = {
    validation: {
        SdvmlValidator: SdvmlValidator;
    };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SdvmlServices = LangiumServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SdvmlModule: Module<
    SdvmlServices,
    PartialLangiumServices & SdvmlAddedServices
> = {
    validation: {
        SdvmlValidator: () => new SdvmlValidator(),
    },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSdvmlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSprottySharedServices;
    Sdvml: SdvmlServices;
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SdvmlGeneratedSharedModule,
        SprottySharedModule
        );
    

const Sdvml = inject(
        createDefaultModule({ shared }), // Pass the *instance* of shared services here
        SprottyDefaultModule, // <-- Place this first to extend LangiumServices with 'diagram'
        SdvmlSprottyModule,   // Your custom diagram generator binding (adds to 'diagram')
        SdvmlGeneratedModule, // Your core generated language services
        SdvmlModule
    ); 


    // const Sdvml = inject(
    //     createDefaultModule({ shared }),
    //     SdvmlGeneratedModule,
    //     SdvmlModule
    // );

//    // Combine the default Sprotty module with your custom Sprotty module
//     const sdvmlSprotty = createDefaultModule({
//         shared,
//         ...SprottyDefaultModule, // Provides core Sprotty Langium services
//         ...SdvmlSprottyModule    // Provides your custom diagram generator binding
//     });

    shared.ServiceRegistry.register(Sdvml);


    registerValidationChecks(Sdvml);
    return { shared, Sdvml };


    // shared.ServiceRegistry.register(Sdvml);
    // registerValidationChecks(Sdvml);
    // if (!context.connection) {
    //     // We don't run inside a language server
    //     // Therefore, initialize the configuration provider instantly
    //     shared.workspace.ConfigurationProvider.initialized({});
    // }
    // return { shared, Sdvml };
}
